// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/763/C 2600
// https://codeforces.com/problemset/status/763/problem/C?friends=on
func Test_cf763C(t *testing.T) {
	testCases := [][2]string{
		{
			`17 5
0 2 4 13 15`,
			`13 2`,
		},
		{
			`17 5
0 2 4 13 14`,
			`-1`,
		},
		{
			`5 3
1 2 3`,
			`3 4`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf763C)
}
