// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/773/D 2700
// https://codeforces.com/problemset/status/773/problem/D?friends=on
func Test_cf773D(t *testing.T) {
	testCases := [][2]string{
		{
			`3
1 2
3`,
			`2
2
3`,
		},
		{
			`6
2 9 9 6 6
7 1 9 10
9 2 5
4 10
8`,
			`6
5
7
5
7
11`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf773D)
}
