// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/2014/H 1900
// https://codeforces.com/problemset/status/2014/problem/H?friends=on
func Test_cf2014H(t *testing.T) {
	testCases := [][2]string{
		{
			`2
3 3
1 2 2
1 2
1 3
2 3
5 3
2 1 2 1 1
1 2
1 3
4 5`,
			`NO
NO
YES
NO
NO
YES`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf2014H)
}
