// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/2057/G 3000
// https://codeforces.com/problemset/status/2057/problem/G?friends=on
func Test_cf2057G(t *testing.T) {
	testCases := [][2]string{
		{
			`3
3 3
.#.
###
.#.
2 6
######
######
3 7
###....
#.#.###
###....`,
			`.#.
#S#
.#.
#S##S#
#S##S#
S#S....
#.#.S#S
S#S....`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf2057G)
}
