// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/659/G 2300
// https://codeforces.com/problemset/status/659/problem/G?friends=on
func Test_cf659G(t *testing.T) {
	testCases := [][2]string{
		{
			`2
1 1`,
			`0`,
		},
		{
			`3
3 4 2`,
			`13`,
		},
		{
			`15
2 72 77 69 62 73 58 9 4 95 97 14 41 79 34`,
			`944598823`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf659G)
}
