// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/582/C 2400
// https://codeforces.com/problemset/status/582/problem/C?friends=on
func Test_cf582C(t *testing.T) {
	testCases := [][2]string{
		{
			`4
7 1 2 3`,
			`2`,
		},
		{
			`2
2 1`,
			`1`,
		},
		{
			`3
1 1 1`,
			`6`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf582C)
}
