// Generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test_c(t *testing.T) {
	if err := testutil.RunLeetCodeFuncWithFile(t, longestSubarray, "c.txt", 0); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode.cn/contest/weekly-contest-516/problems/longest-subarray-with-at-most-k-distinct-prime-factors/
// https://leetcode.cn/problems/longest-subarray-with-at-most-k-distinct-prime-factors/
