// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/464/D 2700
// https://codeforces.com/problemset/status/464/problem/D?friends=on
func Test_cf464D(t *testing.T) {
	testCases := [][2]string{
		{
			`1 3`,
			`1.0000000000`,
		},
		{
			`2 1`,
			`2.3333333333`,
		},
		{
			`10 2`,
			`15.9380768924`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf464D)
}
