// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1905/F 2600
// https://codeforces.com/problemset/status/1905/problem/F?friends=on
func Test_cf1905F(t *testing.T) {
	testCases := [][2]string{
		{
			`5
5
1 2 3 4 5
5
2 1 3 4 5
7
2 1 5 3 7 6 4
6
2 3 5 4 1 6
7
7 6 5 4 3 2 1`,
			`3
5
2
3
2`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1905F)
}
