// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1906/L 2500
// https://codeforces.com/problemset/status/1906/problem/L?friends=on
func Test_cf1906L(t *testing.T) {
	testCases := [][2]string{
		{
			`6 4`,
			`(())()`,
		},
		{
			`6 3`,
			`(()())`,
		},
		{
			`4 1`,
			`-1`,
		},
		{
			`14 11`,
			`()((())()())()`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1906L)
}
