// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1942/G 2800
// https://codeforces.com/problemset/status/1942/problem/G?friends=on
func Test_cf1942G(t *testing.T) {
	testCases := [][2]string{
		{
			`4
1 1 1
0 0 0
5 3 7
3366 1434 1234`,
			`903173463
1
35118742
398952013`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1942G)
}
