// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/913/F 2800
// https://codeforces.com/problemset/status/913/problem/F?friends=on
func Test_cf913F(t *testing.T) {
	testCases := [][2]string{
		{
			`3
1 2`,
			`4`,
		},
		{
			`3
4 6`,
			`142606340`,
		},
		{
			`4
1 2`,
			`598946623`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf913F)
}
