// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/949/E 2700
// https://codeforces.com/problemset/status/949/problem/E?friends=on
func Test_cf949E(t *testing.T) {
	testCases := [][2]string{
		{
			`1
9`,
			`2
1 8`,
		},
		{
			`5
-1 3 0 4 7`,
			`3
4 -1 4`,
		},
		{
			`4
2 -2 14 18`,
			`3
-2 2 16`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf949E)
}
