// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/954/H 2500
// https://codeforces.com/problemset/status/954/problem/H?friends=on
func Test_cf954H(t *testing.T) {
	testCases := [][2]string{
		{
			`4
2 2 2`,
			`14 19 20 20 16 16`,
		},
		{
			`3
2 3`,
			`8 13 6 9`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf954H)
}
