// Code generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test(t *testing.T) {
	t.Log("Current test is [c]")
	examples := [][]string{
		{
			`[[1,1,0],[0,1,0],[0,1,0]]`, `[[0,0,0],[0,1,1],[0,0,1]]`, 
			`3`,
		},
		{
			`[[1]]`, `[[1]]`, 
			`1`,
		},
		{
			`[[0]]`, `[[0]]`, 
			`0`,
		},
		
	}
	targetCaseNum := 0 // -1
	if err := testutil.RunLeetCodeFuncWithExamples(t, largestOverlap, examples, targetCaseNum); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode-cn.com/contest/weekly-contest-84/problems/image-overlap/
