// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/2208/C 1300
// https://codeforces.com/problemset/status/2208/problem/C?friends=on
func Test_cf2208C(t *testing.T) {
	testCases := [][2]string{
		{
			`2
2
10 0
20 5
3
10 5
10 80
20 5`,
			`30.0000000000
29.0000000000`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf2208C)
}
