// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/2215/A 1700
// https://codeforces.com/problemset/status/2215/problem/A?friends=on
func Test_cf2215A(t *testing.T) {
	testCases := [][2]string{
		{
			`6
1 1 3 4
2026
3 2 10 20
31 41 59
4 3 3 4
1 2 3 4
6 4 9 20
18 27 180 9 45 99
7 4 3 5
6 7 14 12 100 78 4
9 4 244 353
9982 4435 3998 2443 5399 8244 3539 9824 4353`,
			`1
11
3
0
4
569`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf2215A)
}
