// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/2223/C 2300
// https://codeforces.com/problemset/status/2223/problem/C?friends=on
func Test_cf2223C(t *testing.T) {
	testCases := [][2]string{
		{
			`2
3 1
1 1
10 20
4
10 5
1 2 2 2 1 1 3 4 5
1 2 3 4 5 6 7 8 9
1 2 3 4 5`,
			`2
6 7 9 6 7`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf2223C)
}
