// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/2228/D 1900
// https://codeforces.com/problemset/status/2228/problem/D?friends=on
func Test_cf2228D(t *testing.T) {
	testCases := [][2]string{
		{
			`5
4
1 1
2 2
3 3
4 4
4
1 4
4 1
1 1
4 4
8
7 2
5 7
2 7
1 3
6 7
3 6
7 5
1 6
8
6 1
3 6
1 4
1 1
4 2
5 5
3 4
4 1
6
5 5
5 4
3 5
1 5
5 3
2 2`,
			`0
1
12
8
4`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf2228D)
}
