// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/2241/E 1600
// https://codeforces.com/problemset/status/2241/problem/E?friends=on
func Test_cf2241E(t *testing.T) {
	testCases := [][2]string{
		{
			`4
5
1 1 1 1 1
1 2
2 3
2 4
4 5
10
1 2 3 4 5 6 7 8 9 10
1 3
2 6
6 7
5 4
8 3
3 4
4 6
9 1
10 2
6
12 6 3 18 9 2
3 4
4 5
2 6
6 1
4 2
8
3 16 9 1 8 16 4 9
2 1
3 1
4 3
3 5
6 3
4 7
8 1`,
			`10
48
0
40`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf2241E)
}
