// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/2241/C 1000
// https://codeforces.com/problemset/status/2241/problem/C?friends=on
func Test_cf2241C(t *testing.T) {
	testCases := [][2]string{
		{
			`4
4
0000
3
110
6
110011
6
101100`,
			`1
2
1
1`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf2241C)
}
