// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/2244/C 1100
// https://codeforces.com/problemset/status/2244/problem/C?friends=on
func Test_cf2244C(t *testing.T) {
	testCases := [][2]string{
		{
			`4
5 2 3
5 4 3 2 1
6 2 4
2 1 4 3 6 5
4 2 2
1 2 3 4
5 2 3
1 2 3 5 4`,
			`YES
NO
YES
YES`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf2244C)
}
