// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/2252/D 1700
// https://codeforces.com/problemset/status/2252/problem/D?friends=on
func Test_cf2252D(t *testing.T) {
	testCases := [][2]string{
		{
			`3
10
100 108 114 118 120 5 7 19 13 11
3
1 2 3
4
10 10 8 4`,
			`100 102 106 112 120 5 -1 -3 -1 11 
1 2 3 
10 6 4 4`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf2252D)
}
