// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/2252/C 1400
// https://codeforces.com/problemset/status/2252/problem/C?friends=on
func Test_cf2252C(t *testing.T) {
	testCases := [][2]string{
		{
			`2
2 3
10 20
2 2 2
5 5 5
3 1
100 100 100
1
2
3`,
			`2
1`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf2252C)
}
