// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1418/G 2500
// https://codeforces.com/problemset/status/1418/problem/G?friends=on
func Test_cf1418G(t *testing.T) {
	testCases := [][2]string{
		{
			`9
1 2 2 2 1 1 2 2 2`,
			`3`,
		},
		{
			`10
1 2 3 4 1 2 3 1 2 3`,
			`0`,
		},
		{
			`12
1 2 3 4 3 4 2 1 3 4 2 1`,
			`1`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1418G)
}
