// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1477/D 2800
// https://codeforces.com/problemset/status/1477/problem/D?friends=on
func Test_cf1477D(t *testing.T) {
	testCases := [][2]string{
		{
			`3
4 2
1 2
3 4
6 4
1 2
1 3
3 5
3 6
2 1
1 2`,
			`1 2 3 4
3 4 1 2
2 3 4 1 6 5
1 4 3 2 5 6
1 2
1 2`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1477D)
}
