// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1620/F 2800
// https://codeforces.com/problemset/status/1620/problem/F?friends=on
func Test_cf1620F(t *testing.T) {
	testCases := [][2]string{
		{
			`4
3
1 2 3
6
1 3 2 6 5 4
4
4 1 3 2
8
3 2 1 6 7 8 5 4`,
			`YES
1 2 3
NO
YES
-4 -1 -3 -2
YES
-3 -2 1 6 7 -8 -5 -4`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1620F)
}
