// Generated by copypasta/template/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// https://codeforces.com/problemset/problem/1679/F 2600
// https://codeforces.com/problemset/status/1679/problem/F?friends=on
func Test_cf1679F(t *testing.T) {
	testCases := [][2]string{
		{
			`1
0`,
			`10`,
		},
		{
			`2
1
0 1`,
			`99`,
		},
		{
			`2
9
0 1
1 2
2 3
3 4
4 5
5 6
6 7
7 8
8 9`,
			`91`,
		},
		{
			`5
6
0 1
0 9
1 5
2 5
2 8
4 8`,
			`77080`,
		},
	}
	testutil.AssertEqualStringCase(t, testCases, 0, cf1679F)
}
