// Generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/leetcode/testutil"
	"testing"
)

func Test_b(t *testing.T) {
	if err := testutil.RunLeetCodeFuncWithFile(t, findDisappearedNumbers, "b.txt", 0); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode.cn/contest/weekly-contest-516/problems/find-all-numbers-disappeared-in-an-array-ii/
// https://leetcode.cn/problems/find-all-numbers-disappeared-in-an-array-ii/
