// Code generated by copypasta/template/atcoder/generator_test.go
package main

import (
	"github.com/EndlessCheng/codeforces-go/main/testutil"
	"testing"
)

// 题目：https://atcoder.jp/contests/abc250/tasks/abc250_e ~CF1786 1421
// 提交：https://atcoder.jp/contests/abc250/submit?taskScreenName=abc250_e
// 对拍：https://atcoder.jp/contests/abc250/submissions?f.LanguageName=Go&f.Status=AC&f.Task=abc250_e&orderBy=source_length
// 最短：https://atcoder.jp/contests/abc250/submissions?f.Status=AC&f.Task=abc250_e&orderBy=source_length
func Test_e(t *testing.T) {
	testCases := [][2]string{
		{
			`5
1 2 3 4 5
1 2 2 4 3
7
1 1
2 2
2 3
3 3
4 4
4 5
5 5`,
			`Yes
Yes
Yes
No
No
Yes
No`,
		},
		
	}
	testutil.AssertEqualStringCase(t, testCases, 0, run)
}
